on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        elasticsearch:
        - plainpicture/elasticsearch:2.4.1_delete-by-query
        - elasticsearch:5.4
        - docker.elastic.co/elasticsearch/elasticsearch:6.7.0
        - docker.elastic.co/elasticsearch/elasticsearch:7.0.0
        - docker.elastic.co/elasticsearch/elasticsearch:7.9.0
        ruby:
        - 2.5
        - 2.6
        - 2.7
    services:
      elasticsearch:
        image: ${{ matrix.elasticsearch }}
        env:
          discovery.type: single-node
        ports:
          - 9200:9200
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: bundle
    - run: sleep 10
    - run: bundle exec rspec
    - run: bundle exec rubocop
